In [1]:
import pandas as pd

In [102]:
df = pd.read_csv("../_output/experiments_result.csv", index_col=False).drop("Unnamed: 0", axis=1)
df["embeddings_type"][df["embeddings_type"] == "bert_small"] = "bert_small (256)"
df["embeddings_type"][df["embeddings_type"] == "bert_tiny"] = "bert_tiny (128)"

/var/folders/m2/659rrfsx63db1lpvyxrqtf9h0000gn/T/ipykernel_80003/4032367051.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["embeddings_type"][df["embeddings_type"] == "bert_small"] = "bert_small (256)"
/var/folders/m2/659rrfsx63db1lpvyxrqtf9h0000gn/T/ipykernel_80003/4032367051.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["embeddings_type"][df["embeddings_type"] == "bert_tiny"] = "bert_tiny (128)"

In [104]:
df.head(10).sort_values(["name"], ascending=False)

,accuracuy,precision,recall,f1_score,name,embeddings_type,data,best_params,is_train
2,0.419337,0.595205,0.412101,0.448591,SVC,tfidf,title,{},True
3,0.378000,0.550916,0.378000,0.406351,SVC,tfidf,title,{},False
8,0.592102,0.656071,0.581140,0.591495,SVC,tfidf,synopsis,{},True
9,0.564667,0.629705,0.564667,0.566598,SVC,tfidf,synopsis,{},False
4,0.296208,0.355724,0.294251,0.292273,NaiveBayes,tfidf,title,{},True
5,0.285333,0.360068,0.285333,0.281771,NaiveBayes,tfidf,title,{},False
0,0.782496,0.794182,0.783729,0.786213,MLP,tfidf,title,{},True
1,0.486333,0.493487,0.486333,0.487366,MLP,tfidf,title,{},False
6,0.886469,0.887748,0.886303,0.886681,MLP,tfidf,synopsis,{},True
7,0.635000,0.640261,0.635000,0.636059,MLP,tfidf,synopsis,{},False

### Comparing F1-scores of all models

In [107]:
df["exp"] = df["embeddings_type"] + "_" + df["data"]
df2 = df[~df.is_train].sort_values(["data"], ascending=False)
result = df2.pivot(index=["embeddings_type", "data"], columns="name", values=["f1_score"])

In [108]:
columns_ordering = [("f1_score","NaiveBayes"), ("f1_score","SVC"), ("f1_score","MLP")]

In [109]:
tmp = result.reset_index()
embs_ordering = ["bert_small (256)", "bert_tiny (128)", "w2v", "tfidf"]
tmp["sortingval"] = tmp.embeddings_type.apply(lambda x: embs_ordering.index(x))
tmp = tmp.sort_values(["sortingval", "data"], ascending=False)
tmp.set_index(["embeddings_type", "data"]).drop("sortingval", axis=1)[columns_ordering]

                            f1_score
name                      NaiveBayes       SVC       MLP
embeddings_type  data
tfidf            title      0.281771  0.406351  0.487366
                 synopsis   0.379795  0.566598  0.636059
                 both       0.338183  0.625928  0.679674
w2v              title      0.303973  0.527074  0.552471
                 synopsis   0.490822  0.640584  0.695595
                 both       0.464542  0.691274  0.698313
bert_tiny (128)  title      0.372541  0.524410  0.518649
                 synopsis   0.479909  0.615487  0.628836
                 both       0.496670  0.678257  0.662607
bert_small (256) title      0.356812  0.588648  0.570283
                 synopsis   0.457391  0.683528  0.681494
                 both       0.463146  0.717195  0.711201